name: Hugo Build and Deploy

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.128.0'  # 替换成你实际用的 Hugo 版本
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to blog-freezz
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          external_repository: freefish100/blog-freezz
          publish_dir: ./public
          publish_branch: main
